apiVersion : apps/v1
kind: Deployment
metadata:
  name: samplewebapp 
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samplewebapp
  template:
    metadata:
      labels:
        app: samplewebapp 
    spec:
      containers:
        - name: samplewebapp 
          image: demoacr24.azurecr.io/webapp
          ports:
          - containerPort: 80